/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static abstractt.ClaseAbstracta.dialogoConfirmacionSiNo;
import abstractt.TextField;
import domain.Animal;
import static domain.Animal.EEid;
import static domain.Animal.animalTodos;
import static domain.Animal.areteSiniiga;
import static domain.Animal.cargararete_visuals;
import static domain.Animal.idAnimalAreteElectronico;
import static domain.ClaseMovimiento.cargarClaseMovimiento;
import static domain.ClaseMovimiento.idClaseDescripcion;
import static domain.CorralAnimal.corralAnimal;
import static domain.Movimiento.cargarMovimientosSalida;
import domain.ParametrosSP;
import domain.SR232;
import static gui.Desktop.rancho;
import static gui.Desktop.manejadorBD;
import static gui.Login.gs_mensaje;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Developer GAGS
 */
public class BusquedaAnimal extends javax.swing.JFrame {//JDialog { //

    /**
     * Creates new form SalidaGanado
     */
    public BusquedaAnimal(Desktop parent) {
        // super(parent, modal);
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);

        animal = new Animal();

        this.tagIdSelector.addArray(cargararete_visuals());

        cargarPuertos();

        stick = new SR232(puertoStick, 1, parent, 7);
        stick.setEID(tf_Eid);   //  tf_Eid::tf_numeroPedido

        stick.start();

        tagIdSelector.ActionTranferfocus = false;

        cargarAnimales();

        this.setTitle(this.getTitle() + " " + rancho.descripcion);

        Image i = null;
        i = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo tru-test.png"));
        setIconImage(i);

        fondo1.cargar(getSize());
    }

    public void cargarPuertos() {

        manejadorBD.consulta(
                "SELECT puerto_baston, puerto_bascula "
                + "FROM configuracion ");

        if (manejadorBD.getRowCount() > 0) {

            puertoStick = manejadorBD.getValorString(0, 0);
            puertoBascula = manejadorBD.getValorString(0, 1);
        }
    }

    String puertoStick, puertoBascula;
    private SR232 stick;
    private Integer idClaseMovimiento;
    private Integer id_destino;

    public void cargarAnimales() {

        t_animales = animalTodos(t_animales);

        if (t_animales.getRowCount() > 0) {

            btn_detalles.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tagIdSelector = new abstractt.ComboBox();
        tf_Eid = new abstractt.TextField();
        etiqueta2 = new abstractt.Etiqueta();
        etiqueta3 = new abstractt.Etiqueta();
        etiqueta4 = new abstractt.Etiqueta();
        btn_detalles = new abstractt.Boton();
        tf_areteSiniiga = new abstractt.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_animales = new abstractt.Table();
        etiqueta1 = new abstractt.Etiqueta();
        fondo1 = new abstractt.fondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Animal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tagIdSelector.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tagIdSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagIdSelectorActionPerformed(evt);
            }
        });
        jPanel4.add(tagIdSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 200, 20));

        tf_Eid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Eid.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tf_Eid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_EidFocusLost(evt);
            }
        });
        tf_Eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_EidActionPerformed(evt);
            }
        });
        jPanel4.add(tf_Eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, 20));

        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta2.setText("Arete Visual: ");
        jPanel4.add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        etiqueta3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta3.setText("Arete Electrónico");
        jPanel4.add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 100, 20));

        etiqueta4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta4.setText("Arete Siniiga: ");
        jPanel4.add(etiqueta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 20));

        btn_detalles.setText("Detalles");
        btn_detalles.setToolTipText("Muestra las Especificaciones del Animal");
        btn_detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detallesActionPerformed(evt);
            }
        });
        jPanel4.add(btn_detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 25, 150, 40));

        tf_areteSiniiga.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel4.add(tf_areteSiniiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 106, 999, 90));

        t_animales.setForeground(new java.awt.Color(230, 225, 195));
        t_animales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        t_animales.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(t_animales);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 1075, 400));

        etiqueta1.setBackground(new java.awt.Color(95, 84, 88));
        etiqueta1.setForeground(new java.awt.Color(230, 225, 195));
        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1.setText("Busqueda de Animal");
        etiqueta1.setFont(new java.awt.Font("Trebuchet", 1, 48)); // NOI18N
        etiqueta1.setOpaque(true);
        jPanel1.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1133, 80));

        fondo1.setText("fondo1");
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tagIdSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagIdSelectorActionPerformed

        //id_animal = Integer.parseInt(tagIdSelector.getSelectedItem().toString());
        animal.cargarPorAreteVisual(tagIdSelector.getSelectedItem().toString(), "A");

        cargarDatosTag();
    }//GEN-LAST:event_tagIdSelectorActionPerformed

    private void cargarDatosTag() {

        // arete_electronico = EEid(id_animal);
        tf_Eid.setText(animal.arete_electronico);

        //corral = corralAnimal(id_animal);    
        //arete_siniiga = areteSiniiga(id_animal);
        tf_areteSiniiga.setText(animal.arete_siniiga);

        this.t_animales.buscar(animal.arete_electronico, 2, jScrollPane2);
    }

    public void setEid(String eid) {

        //System.out.println("setEid arete_electronico="+arete_electronico);
        animal.cargarPorEid(eid);

        //System.out.println(animal.toString());
        this.tf_Eid.setText(animal.arete_electronico);
        tagIdSelector.setSelectedItem(animal.arete_visual);//id_animal.toString());

        //corral = corralAnimal(id_animal);
        //arete_siniiga = areteSiniiga(id_animal);
        tf_areteSiniiga.setText(animal.arete_siniiga);
    }

    public void cargarDatosEid() {

        animal.cargarPorEid(this.tf_Eid.getText());
        tagIdSelector.setSelectedItem(animal.arete_visual);
        tf_areteSiniiga.setText(animal.arete_siniiga);
    }

    public void cargarDatosSiniiga() {

        animal.cargarPorAreteSiniiga(this.tf_areteSiniiga.getText());

        tf_Eid.setText(animal.arete_electronico);
        tagIdSelector.setSelectedItem(animal.arete_visual);
        //tf_areteSiniiga.setText(animal.arete_siniiga);
    }

    private void tf_EidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_EidFocusLost

        if (true) {
            
            return;
        }
        eid = tf_Eid.getText();
        cargarDatosEid();
    }//GEN-LAST:event_tf_EidFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.stick.setSeguir(false);
    }//GEN-LAST:event_formWindowClosing

    private void tf_EidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_EidActionPerformed

        cargarDatosEid();
    }//GEN-LAST:event_tf_EidActionPerformed

    private void btn_detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detallesActionPerformed

        int fila;

        if (especificacionesAnimal != null) {

            especificacionesAnimal.dispose();
        }

        especificacionesAnimal = new EspecificacionesAnimal(parent);

        fila = t_animales.getSelectedRow();

        if (fila < 0) {

            JOptionPane.showMessageDialog(this, "Seleccione un Animal\n" + manejadorBD.errorSQL, gs_mensaje, JOptionPane.ERROR_MESSAGE);
            return;
        }

        animal.cargarPorId(this.t_animales.getValueAt(fila, 0).toString());

        if (!animal.id_animal.equals("")) {

            especificacionesAnimal.setId_animal(animal.id_animal);
        }
        especificacionesAnimal.setVisible(true);
    }//GEN-LAST:event_btn_detallesActionPerformed

    Desktop parent;
    public EspecificacionesAnimal especificacionesAnimal;
    private Integer id_animal;
    private Integer id_corral;
    private String numeroPedido;
    private String corral, eid;
    private String arete_siniiga;
    private Double peso_actual;
    private Animal animal;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.Boton btn_detalles;
    private abstractt.Etiqueta etiqueta1;
    private abstractt.Etiqueta etiqueta2;
    private abstractt.Etiqueta etiqueta3;
    private abstractt.Etiqueta etiqueta4;
    private abstractt.fondo fondo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private abstractt.Table t_animales;
    private abstractt.ComboBox tagIdSelector;
    private abstractt.TextField tf_Eid;
    private abstractt.TextField tf_areteSiniiga;
    // End of variables declaration//GEN-END:variables
}
