/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.ManejadorBD;
import static domain.Medicina.cargarCodigoMedicinas;
import static domain.UnidadMedida.cargarUnidades;
import static gui.Desktop.manejadorBD;
import static gui.Desktop.rancho;

/**
 *
 * @author Home
 */
public class Compras extends javax.swing.JInternalFrame {

    /**
     * Creates new form IngresoMedicamento
     */
    public Compras() {

        initComponents();
        setTitle(this.getTitle() + " " + rancho.descripcion);
        setResizable(false);

        String titulos[] = {"Partida", "Código", "Medicina", "Cantidad", "Precio Unitario", "Importe"};

        t_medicina.setTitulos(titulos);
        t_medicina.cambiarTitulos();
        t_medicina.setFormato(new int[]{4, 4, 0, 4, 2, 2});
        t_medicina.centrar();

        tf_factura.textFieldSoloNumerosYLetras();
        tf_ordenCompra.textFieldSoloNumeros();
        tf_cantidadIngresada.textFieldSoloNumeros();

        proveedorSelector1.cargar();
        medicinaSelector1.cargar();
        codigoSelector.addArray(cargarCodigoMedicinas());
        UnidadSelector.addArray(cargarUnidades());
    }

    private void cargarMedicina() {

        ManejadorBD mbd = manejadorBD.nuevaConexion();

        mbd.consulta(""
                + "SELECT 	m.codigo, m.nombre, cd.cantidad, 	cd.precio_unitario, cd.importe"
                + "FROM 	compras as c, compra_detalle as cd, 	medicina as m"
                + "WHERE 	cd.id_medicina = m.id_medicina"
                + "AND		cd.id_compra = c.id_compras;");

        this.t_medicina.setModel(mbd);
        if (mbd.getRowCount() > 0) {

            t_medicina.setRowSelectionInterval(0, 0);
        }

//        t_medicina.ocultarcolumna(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fecha1 = new domain.Fecha();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        etiqueta1 = new abstractt.Etiqueta();
        etiqueta2 = new abstractt.Etiqueta();
        etiqueta4 = new abstractt.Etiqueta();
        tf_factura = new abstractt.TextField();
        tf_ordenCompra = new abstractt.TextField();
        proveedorSelector1 = new domain.ProveedorSelector();
        selectorFecha1 = new gui.SelectorFecha();
        jPanel4 = new javax.swing.JPanel();
        etiqueta5 = new abstractt.Etiqueta();
        medicinaSelector1 = new domain.MedicinaSelector();
        etiqueta6 = new abstractt.Etiqueta();
        codigoSelector = new abstractt.ComboBox();
        etiqueta7 = new abstractt.Etiqueta();
        etiqueta8 = new abstractt.Etiqueta();
        etiqueta9 = new abstractt.Etiqueta();
        tf_cantidadIngresada = new abstractt.TextField();
        UnidadSelector = new abstractt.ComboBox();
        tf_precioUnitario = new abstractt.TextFieldMoneda();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_medicina = new abstractt.Table();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(64, 37, 4))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta1.setText("Número de Factura");
        jPanel2.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 20));

        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta2.setText("Proveedor");
        jPanel2.add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));

        etiqueta4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta4.setText("Orden de Compra");
        jPanel2.add(etiqueta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 20));
        jPanel2.add(tf_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 130, 20));
        jPanel2.add(tf_ordenCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 130, 20));
        jPanel2.add(proveedorSelector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 20));
        jPanel2.add(selectorFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 350, 200));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la Medicina", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(64, 37, 4))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta5.setText("Medicamento:");
        jPanel4.add(etiqueta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 20));
        jPanel4.add(medicinaSelector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 130, 20));

        etiqueta6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta6.setText("Código:");
        jPanel4.add(etiqueta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 20));
        jPanel4.add(codigoSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 130, 20));

        etiqueta7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta7.setText("Cantidad ingresada:");
        jPanel4.add(etiqueta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 130, 20));

        etiqueta8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta8.setText("Unidad de Medida:");
        jPanel4.add(etiqueta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, 20));

        etiqueta9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta9.setText("Precio Unitario:");
        jPanel4.add(etiqueta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 130, 20));
        jPanel4.add(tf_cantidadIngresada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, 20));
        jPanel4.add(UnidadSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 20));
        jPanel4.add(tf_precioUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 350, 200));

        t_medicina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(t_medicina);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 800, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.ComboBox UnidadSelector;
    private abstractt.ComboBox codigoSelector;
    private abstractt.Etiqueta etiqueta1;
    private abstractt.Etiqueta etiqueta2;
    private abstractt.Etiqueta etiqueta4;
    private abstractt.Etiqueta etiqueta5;
    private abstractt.Etiqueta etiqueta6;
    private abstractt.Etiqueta etiqueta7;
    private abstractt.Etiqueta etiqueta8;
    private abstractt.Etiqueta etiqueta9;
    private domain.Fecha fecha1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private domain.MedicinaSelector medicinaSelector1;
    private domain.ProveedorSelector proveedorSelector1;
    private gui.SelectorFecha selectorFecha1;
    private abstractt.Table t_medicina;
    private abstractt.TextField tf_cantidadIngresada;
    private abstractt.TextField tf_factura;
    private abstractt.TextField tf_ordenCompra;
    private abstractt.TextFieldMoneda tf_precioUnitario;
    // End of variables declaration//GEN-END:variables
}
