/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Ciudad;
import domain.Estado;
import domain.ParametrosSP;
import domain.Usuario;
import static gui.Desktop.manejadorBD;
import static gui.Login.gs_mensaje;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form crearUsuario
     */
    public CrearUsuario(java.awt.Frame parent) {
        this.parent = parent;
        initComponents();
        Image i = null;
        i = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo tru-test.png"));
        setIconImage(i);
        usuario = new Usuario();
        estado = new Estado();
        ciudad = new Ciudad();
        estadoSelector1.cargar();
        fondo1.cargar(this.getSize());
        this.setResizable(false);
        this.tf_correo.setPlaceholder("ejemplo@gmail.com");
        this.tf_telefono.setPlaceholder("XXX-XXX-XXX-XXXX");
    }

    private void guardarUsuario() {
        String contraseña1 = this.passwordField1.getText();
        String contraseña2 = this.passwordField2.getText();
        if (contraseña1.equals(contraseña2)) {
            usuario.setLog(this.tf_user.getText());
            usuario.setPassword(this.passwordField1.getText());
            usuario.setNombre(this.tf_nombre.getText());
            usuario.setApellido(this.tf_apell.getText());
            estado.cargarPorDescripcion(this.estadoSelector1.getSelectedItem().toString());
            usuario.setEstado(estado);
            ciudad.cargarPorDescripcion(this.ciudadSelector1.getSelectedItem().toString());
            usuario.setCiudad(ciudad);
            usuario.setCorreo(this.tf_correo.getText());
            usuario.setFecha(this.selectorFecha1.getFecha().toString());
            try {
                usuario.setTelefono(tf_telefono.getText());
                manejadorBD.parametrosSP = new ParametrosSP();
                manejadorBD.parametrosSP.agregarParametro(usuario.getLog(), "varLog", "STRING", "IN");
                manejadorBD.parametrosSP.agregarParametro(usuario.getPassword(), "varPassword", "STRING", "IN");
                manejadorBD.parametrosSP.agregarParametro(usuario.getNombre(), "varNombre", "STRING", "IN");
                manejadorBD.parametrosSP.agregarParametro(usuario.getApellido(), "varApellido", "STRING", "IN");
                manejadorBD.parametrosSP.agregarParametro(usuario.getEstado().descripcion, "varId_estado", "STRING", "IN");
                manejadorBD.parametrosSP.agregarParametro(usuario.getCiudad().descripcion, "varId_ciudad", "STRING", "IN");
                manejadorBD.parametrosSP.agregarParametro(usuario.getCorreo(), "varCorreo", "STRING", "IN");
                manejadorBD.parametrosSP.agregarParametro(usuario.getFecha(), "varFecha", "STRING", "IN");
                manejadorBD.parametrosSP.agregarParametro(usuario.getTelefono(), "varTelefono", "STRING", "IN");
                if (manejadorBD.ejecutarSP("{ call agregarUsuario(?,?,?,?,?,?,?,?,?) }") == 0) {

                    JOptionPane.showMessageDialog(this, "Se creó el usuario " + usuario.getLog() + " correctamente", gs_mensaje, JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                } else {

                    JOptionPane.showMessageDialog(this, "Error al crear el usuario " + usuario.getLog(), gs_mensaje, JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception e) {
                JOptionPane.showConfirmDialog(this, "Su número de telefóno esta equivocado", gs_mensaje, JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Tu contraseña no es la misma, vuelve a revisar", gs_mensaje, JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiqueta1 = new abstractt.Etiqueta();
        jPanel2 = new javax.swing.JPanel();
        etiqueta2 = new abstractt.Etiqueta();
        etiqueta3 = new abstractt.Etiqueta();
        etiqueta4 = new abstractt.Etiqueta();
        etiqueta5 = new abstractt.Etiqueta();
        etiqueta6 = new abstractt.Etiqueta();
        etiqueta7 = new abstractt.Etiqueta();
        etiqueta8 = new abstractt.Etiqueta();
        etiqueta9 = new abstractt.Etiqueta();
        etiqueta10 = new abstractt.Etiqueta();
        tf_nombre = new abstractt.TextField();
        tf_apell = new abstractt.TextField();
        tf_user = new abstractt.TextField();
        ciudadSelector1 = new domain.CiudadSelector();
        estadoSelector1 = new domain.EstadoSelector();
        selectorFecha1 = new gui.SelectorFecha();
        tf_telefono = new abstractt.TextField();
        jPanel3 = new javax.swing.JPanel();
        btn_aceptar = new abstractt.Boton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        btn_cancelar = new abstractt.Boton();
        etiqueta11 = new abstractt.Etiqueta();
        tf_correo = new abstractt.TextField();
        passwordField1 = new abstractt.PasswordField();
        passwordField2 = new abstractt.PasswordField();
        fondo1 = new abstractt.fondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta1.setBackground(new java.awt.Color(95, 84, 88));
        etiqueta1.setForeground(new java.awt.Color(230, 225, 195));
        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1.setText("Crea una Cuenta");
        etiqueta1.setFont(new java.awt.Font("Trebuchet", 1, 36)); // NOI18N
        etiqueta1.setOpaque(true);
        jPanel1.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta2.setText("Nombre: ");
        jPanel2.add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 20));

        etiqueta3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta3.setText("Apellidos: ");
        jPanel2.add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 20));

        etiqueta4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta4.setText("Nombre de usuario: ");
        jPanel2.add(etiqueta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 20));

        etiqueta5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta5.setText("Contraseña: ");
        jPanel2.add(etiqueta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 150, 20));

        etiqueta6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta6.setText("Repite contraseña: ");
        jPanel2.add(etiqueta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 20));

        etiqueta7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta7.setText("Estado");
        jPanel2.add(etiqueta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 20));

        etiqueta8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta8.setText("Fecha de Nacimiento: ");
        jPanel2.add(etiqueta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 150, 20));

        etiqueta9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta9.setText("Ciudad");
        jPanel2.add(etiqueta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 150, 20));

        etiqueta10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta10.setText("Teléfono");
        jPanel2.add(etiqueta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 20));
        jPanel2.add(tf_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, 20));
        jPanel2.add(tf_apell, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 180, 20));
        jPanel2.add(tf_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 180, 20));
        jPanel2.add(ciudadSelector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 180, 20));

        estadoSelector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoSelector1ActionPerformed(evt);
            }
        });
        jPanel2.add(estadoSelector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 180, 20));
        jPanel2.add(selectorFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));
        jPanel2.add(tf_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 180, 20));

        jPanel3.setOpaque(false);

        btn_aceptar.setText("Aceptar");
        btn_aceptar.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_aceptar);
        jPanel3.add(filler1);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_cancelar);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, 80));

        etiqueta11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta11.setText("Correo Electrónico: ");
        jPanel2.add(etiqueta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 150, 20));
        jPanel2.add(tf_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 180, 20));
        jPanel2.add(passwordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 180, 20));
        jPanel2.add(passwordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 400, -1));

        fondo1.setText("fondo1");
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoSelector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoSelector1ActionPerformed
        estado.cargarPorDescripcion(estadoSelector1.getSelectedItem().toString());
        this.ciudadSelector1.cargar(estado);
    }//GEN-LAST:event_estadoSelector1ActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        guardarUsuario();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    private Usuario usuario;
    private Estado estado;
    private Ciudad ciudad;
    java.awt.Frame parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.Boton btn_aceptar;
    private abstractt.Boton btn_cancelar;
    private domain.CiudadSelector ciudadSelector1;
    private domain.EstadoSelector estadoSelector1;
    private abstractt.Etiqueta etiqueta1;
    private abstractt.Etiqueta etiqueta10;
    private abstractt.Etiqueta etiqueta11;
    private abstractt.Etiqueta etiqueta2;
    private abstractt.Etiqueta etiqueta3;
    private abstractt.Etiqueta etiqueta4;
    private abstractt.Etiqueta etiqueta5;
    private abstractt.Etiqueta etiqueta6;
    private abstractt.Etiqueta etiqueta7;
    private abstractt.Etiqueta etiqueta8;
    private abstractt.Etiqueta etiqueta9;
    private javax.swing.Box.Filler filler1;
    private abstractt.fondo fondo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private abstractt.PasswordField passwordField1;
    private abstractt.PasswordField passwordField2;
    private gui.SelectorFecha selectorFecha1;
    private abstractt.TextField tf_apell;
    private abstractt.TextField tf_correo;
    private abstractt.TextField tf_nombre;
    private abstractt.TextField tf_telefono;
    private abstractt.TextField tf_user;
    // End of variables declaration//GEN-END:variables
}
