/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Estado;
import domain.Estado;
import domain.Proveedor;
import static gui.Desktop.rancho;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author sperez
 */
public class DialogoEstadoSelector extends javax.swing.JDialog {

    Estado estado;

    /**
     * Creates new form DialogoProveedorSelector
     */
    public DialogoEstadoSelector(java.awt.Frame parent, boolean modal, Estado aEstado) {
        super(parent, modal);
        initComponents();
        
        this.estadoSelector1.cargar();
        estado = new Estado();
        estadoSelector1.setSelectedItem(aEstado.descripcion);
        setEstado = false;
        
        Image i = null;
        i = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo tru-test.png"));
        setIconImage(i);

        this.setTitle(this.getTitle() + " " + rancho.descripcion);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        estadoSelector1 = new domain.EstadoSelector();

        setTitle("Selecciona Estado");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        estadoSelector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoSelector1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(estadoSelector1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(estadoSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setEstado(Estado estado) {
        setEstado = true;
        this.estadoSelector1.setSelectedItem(estado.descripcion);
        setEstado = false;
    }

    
    public Estado getEstado(){
        
        return estadoSelector1.getEstado();
    }

    private void estadoSelector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoSelector1ActionPerformed

        if (!setEstado) {
            
            this.setVisible(false);
        }
    }//GEN-LAST:event_estadoSelector1ActionPerformed

    boolean setEstado;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private domain.EstadoSelector estadoSelector1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
