/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Ciudad;
import domain.Ciudad;
import domain.Estado;
import domain.Estado;
import static gui.Desktop.rancho;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author sperez
 */
public class DialogoCiudadSelector extends javax.swing.JFrame {

    Ciudad ciudad;
    Estado estado;

    /**
     * Creates new form DialogoProveedorSelector
     */
    public DialogoCiudadSelector(java.awt.Frame parent, Estado aEstado, Ciudad aCiudad) {
//        super(parent, modal);
        initComponents();
        estado = new Estado();
        estado.cargarPorDescripcion(aEstado.descripcion);

        this.ciudadSelector1.cargar(estado);
        ciudad = new Ciudad();
        ciudadSelector1.setSelectedItem(aCiudad.descripcion);
        setCiudad = false;

        Image i = null;
        i = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo tru-test.png"));
        setIconImage(i);

        this.setTitle(this.getTitle() + " " + rancho.descripcion);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ciudadSelector1 = new domain.CiudadSelector();

        setTitle("Selecciona Ciudad");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ciudadSelector1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadSelector1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ciudadSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ciudadSelector1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCiudad(Ciudad ciudad) {
        setCiudad = true;
        this.ciudadSelector1.setSelectedItem(ciudad.descripcion);
        setCiudad = false;
    }

    public Ciudad getCiudad() {

        return ciudadSelector1.getCiudad();
    }

    private void ciudadSelector1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadSelector1ActionPerformed

        if (!setCiudad) {

            this.setVisible(false);
        }
    }//GEN-LAST:event_ciudadSelector1ActionPerformed

    boolean setCiudad;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private domain.CiudadSelector ciudadSelector1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
