/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import abstractt.Table;
import domain.Animal;
import domain.ManejadorBD;
import domain.Rancho;
import domain.Seguridad;
import giovynet.nativelink.SerialPort;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.DateAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYItemRenderer;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.time.Day;
import org.jfree.data.time.TimeSeries;
import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.data.xy.XYDataset;
import org.jfree.ui.RectangleInsets;

/**
 *
 * @author
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Inicio() {//ManejadorBD mBD) {

        initComponents();
        setLocationRelativeTo(null);

        ImageIcon fot = (ImageIcon) jLabel1.getIcon();
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);

        fot = (ImageIcon) jtextfield.getIcon();
        icono = new ImageIcon(fot.getImage().getScaledInstance(jtextfield.getWidth(), jtextfield.getHeight(), Image.SCALE_DEFAULT));
        jtextfield.setIcon(icono);

        Image i = null;
        i = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo tru-test.png"));
        setIconImage(i);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_aplicacionMedicinas = new javax.swing.JButton();
        btn_IngresoAnimales = new javax.swing.JButton();
        btn_trasladoGanado = new javax.swing.JButton();
        btn_gestionMedicinas = new javax.swing.JButton();
        btn_salidaGanado = new javax.swing.JButton();
        btn_Hospital = new javax.swing.JButton();
        btn_Muertes = new javax.swing.JButton();
        btn_configuracion = new javax.swing.JButton();
        btn_ReporteTraslados = new javax.swing.JButton();
        btn_reporteSesiones = new javax.swing.JButton();
        jtextfield = new javax.swing.JLabel();
        btn_BusquedaAnimal = new javax.swing.JButton();
        btn_Partos = new javax.swing.JButton();
        btn_Exportar = new javax.swing.JButton();
        btn_tratamientos = new javax.swing.JButton();
        btn_sementales = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Feedlot Manager Main");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo tru-test.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 110, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTROL DE PRODUCCION DE HATOS GANADEROS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 280, -1));

        jLabel3.setFont(new java.awt.Font("Vijaya", 1, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Feedlot Manager");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 450, 60));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 90));

        btn_aplicacionMedicinas.setBackground(new java.awt.Color(255, 255, 255));
        btn_aplicacionMedicinas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_aplicacionMedicinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pill.png"))); // NOI18N
        btn_aplicacionMedicinas.setText("                    Aplicacion de Medicinas  ");
        btn_aplicacionMedicinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aplicacionMedicinasActionPerformed(evt);
            }
        });
        jPanel3.add(btn_aplicacionMedicinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 290, 55));

        btn_IngresoAnimales.setBackground(new java.awt.Color(255, 255, 255));
        btn_IngresoAnimales.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_IngresoAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        btn_IngresoAnimales.setText("                   Ingreso de Animales             ");
        btn_IngresoAnimales.setIconTextGap(1);
        btn_IngresoAnimales.setVerifyInputWhenFocusTarget(false);
        btn_IngresoAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresoAnimalesActionPerformed(evt);
            }
        });
        jPanel3.add(btn_IngresoAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 290, 55));

        btn_trasladoGanado.setBackground(new java.awt.Color(255, 255, 255));
        btn_trasladoGanado.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_trasladoGanado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/table_relationship.png"))); // NOI18N
        btn_trasladoGanado.setText("                  Traslados de Ganado           ");
        btn_trasladoGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trasladoGanadoActionPerformed(evt);
            }
        });
        jPanel3.add(btn_trasladoGanado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 290, 55));

        btn_gestionMedicinas.setBackground(new java.awt.Color(255, 255, 255));
        btn_gestionMedicinas.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_gestionMedicinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/injection.png"))); // NOI18N
        btn_gestionMedicinas.setText("                 Gestion de Medicinas           ");
        btn_gestionMedicinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestionMedicinasActionPerformed(evt);
            }
        });
        jPanel3.add(btn_gestionMedicinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 290, 55));

        btn_salidaGanado.setBackground(new java.awt.Color(255, 255, 255));
        btn_salidaGanado.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_salidaGanado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/table_export.png"))); // NOI18N
        btn_salidaGanado.setText("                     Salida de Ganado               ");
        btn_salidaGanado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salidaGanadoActionPerformed(evt);
            }
        });
        jPanel3.add(btn_salidaGanado, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 290, 55));

        btn_Hospital.setBackground(new java.awt.Color(255, 255, 255));
        btn_Hospital.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_Hospital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/hospital.png"))); // NOI18N
        btn_Hospital.setText("                            Hospital                         ");
        btn_Hospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HospitalActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Hospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 290, 55));

        btn_Muertes.setBackground(new java.awt.Color(255, 255, 255));
        btn_Muertes.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_Muertes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/skull_old.png"))); // NOI18N
        btn_Muertes.setText("                           Muertes                          ");
        btn_Muertes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MuertesActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Muertes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 290, 55));

        btn_configuracion.setBackground(new java.awt.Color(255, 255, 255));
        btn_configuracion.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/configure_cluster.png"))); // NOI18N
        btn_configuracion.setText("                       Configuración                    ");
        btn_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionActionPerformed(evt);
            }
        });
        jPanel3.add(btn_configuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 290, 55));

        btn_ReporteTraslados.setBackground(new java.awt.Color(255, 255, 255));
        btn_ReporteTraslados.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_ReporteTraslados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/report_green.png"))); // NOI18N
        btn_ReporteTraslados.setText("                 Reporte de Traslados            ");
        btn_ReporteTraslados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReporteTrasladosActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ReporteTraslados, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 290, 55));

        btn_reporteSesiones.setBackground(new java.awt.Color(255, 255, 255));
        btn_reporteSesiones.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_reporteSesiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chart_pie_title.png"))); // NOI18N
        btn_reporteSesiones.setText("                 Reporte de Sesiones             ");
        btn_reporteSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteSesionesActionPerformed(evt);
            }
        });
        jPanel3.add(btn_reporteSesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 290, 55));

        jtextfield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Imagen para el menu principal .png"))); // NOI18N
        jPanel3.add(jtextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 290, 230));

        btn_BusquedaAnimal.setBackground(new java.awt.Color(255, 255, 255));
        btn_BusquedaAnimal.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_BusquedaAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/page_find_48x48.png"))); // NOI18N
        btn_BusquedaAnimal.setText("                     Busqueda Animal               ");
        btn_BusquedaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BusquedaAnimalActionPerformed(evt);
            }
        });
        jPanel3.add(btn_BusquedaAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 290, 55));

        btn_Partos.setBackground(new java.awt.Color(255, 255, 255));
        btn_Partos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_Partos.setText("                  Partos");
        btn_Partos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PartosActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Partos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 290, 55));

        btn_Exportar.setBackground(new java.awt.Color(255, 255, 255));
        btn_Exportar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_Exportar.setText("Exportar Datos");
        btn_Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 290, 55));

        btn_tratamientos.setBackground(new java.awt.Color(255, 255, 255));
        btn_tratamientos.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_tratamientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pill.png"))); // NOI18N
        btn_tratamientos.setText("                             Tratamientos              ");
        btn_tratamientos.setToolTipText("");
        btn_tratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tratamientosActionPerformed(evt);
            }
        });
        jPanel3.add(btn_tratamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 290, 55));

        btn_sementales.setBackground(new java.awt.Color(255, 255, 255));
        btn_sementales.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btn_sementales.setText("                             Sementales              ");
        btn_sementales.setToolTipText("");
        btn_sementales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sementalesActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sementales, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 290, 55));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_IngresoAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresoAnimalesActionPerformed
    }//GEN-LAST:event_btn_IngresoAnimalesActionPerformed

    private void btn_trasladoGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trasladoGanadoActionPerformed
    }//GEN-LAST:event_btn_trasladoGanadoActionPerformed

    private void btn_gestionMedicinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestionMedicinasActionPerformed
    }//GEN-LAST:event_btn_gestionMedicinasActionPerformed

    private void btn_salidaGanadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salidaGanadoActionPerformed
    }//GEN-LAST:event_btn_salidaGanadoActionPerformed

    private void btn_HospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HospitalActionPerformed
    }//GEN-LAST:event_btn_HospitalActionPerformed

    private void btn_MuertesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MuertesActionPerformed
    }//GEN-LAST:event_btn_MuertesActionPerformed


    private void btn_configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionActionPerformed
    }//GEN-LAST:event_btn_configuracionActionPerformed

    private void btn_ReporteTrasladosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReporteTrasladosActionPerformed
    }//GEN-LAST:event_btn_ReporteTrasladosActionPerformed

    private void btn_reporteSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteSesionesActionPerformed
    }//GEN-LAST:event_btn_reporteSesionesActionPerformed

    private void btn_BusquedaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BusquedaAnimalActionPerformed
    }//GEN-LAST:event_btn_BusquedaAnimalActionPerformed

    private void btn_aplicacionMedicinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aplicacionMedicinasActionPerformed
    }//GEN-LAST:event_btn_aplicacionMedicinasActionPerformed

    private void btn_PartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PartosActionPerformed
    }//GEN-LAST:event_btn_PartosActionPerformed

    private void btn_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportarActionPerformed
        
        try {
            
            Runtime r = Runtime.getRuntime();
            Process p = null;
            p = r.exec("java -jar feetlotFTP.jar");
        } catch (IOException ex) {
            
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ExportarActionPerformed

    private void btn_tratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tratamientosActionPerformed
    }//GEN-LAST:event_btn_tratamientosActionPerformed

    private void btn_sementalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sementalesActionPerformed
    }//GEN-LAST:event_btn_sementalesActionPerformed

    /**
     * @return the manejadorBD
     */
//    public ManejadorBD getManejadorBD() {
//        
//        return manejadorBD;
//    }
//
//    /**
//     * @param aManejadorBD the manejadorBD to set
//     */
//    public void setManejadorBD(ManejadorBD aManejadorBD) {
//
//        manejadorBD = aManejadorBD;
//    }
    
//    public static ManejadorBD manejadorBD = null;
//    public static Rancho rancho;
//    
//    public static BusquedaAnimalSelector busquedaAnimalSelector;
//    public Sementales sementales;
//    public Partos partos;
//    public AdministracionGrupos administracionGrupos;
//    public MedicinasAnimalGrupo medicinasAnimalGrupo;
//    public SalidaGanadoGrupo salidaGanadoGrupo;
//    public Traslados grupos;
//    public BajasMuerte bajasMuerte;
//    public BusquedaAnimal busquedaAnimal;
//    public AdministracionTratamientos administracionTratamiento;
//    private AdministracionMedicamentos administracionMedicamentos;
//    private VisualizacionHospital visualizacionHospital;
//    private VisualizacionMuertes visualizacionMuertes;
//    private Configuracion configuracion;
//    private RegistroTrasladoGanado trasladoGanado;
//    private ReporteSesiones reporteSesiones;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BusquedaAnimal;
    private javax.swing.JButton btn_Exportar;
    private javax.swing.JButton btn_Hospital;
    private javax.swing.JButton btn_IngresoAnimales;
    private javax.swing.JButton btn_Muertes;
    private javax.swing.JButton btn_Partos;
    private javax.swing.JButton btn_ReporteTraslados;
    private javax.swing.JButton btn_aplicacionMedicinas;
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JButton btn_gestionMedicinas;
    private javax.swing.JButton btn_reporteSesiones;
    private javax.swing.JButton btn_salidaGanado;
    private javax.swing.JButton btn_sementales;
    private javax.swing.JButton btn_trasladoGanado;
    private javax.swing.JButton btn_tratamientos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jtextfield;
    // End of variables declaration//GEN-END:variables
}
