package gui;

import abstractt.Table;
import domain.Animal;
import static domain.Animal.animalGrupo;
import domain.AnimalGrupo;
import domain.Excel;
import static domain.Medicina.cargarCodigoMedicinas;
import static domain.Medicina.cargarMedicinas;
import static domain.Medicina.leerMedicinaAnimal;
import domain.ParametrosSP;
import domain.SR232;
import domain.Usuario;
import static gui.Desktop.rancho;
import static gui.Desktop.manejadorBD;
import static gui.Login.gs_mensaje;
import static gui.Login.usuario_activo;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javafx.scene.Parent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Developer GAGS
 */
public class MedicinasAnimalGrupo extends javax.swing.JFrame {//JDialog {

    private SR232 stick;
    private String puertoStick;

    /**
     * Creates new form MedicinasAnimal
     */
    public MedicinasAnimalGrupo(Desktop parent) {
        this.parent = parent;

        initComponents();
        setLocationRelativeTo(null);
        //animal = aAnimal;
        animal = new Animal();
        animal.cargarPorEid("");
        Dimension d;

        d = medicamentoSelector.getSize();
        codigoSelector.addArray(cargarCodigoMedicinas());
        medicamentoSelector.addArray(cargarMedicinas());
        medicamentoSelector.setSize(d);
        //"id Medicina",
        /*
         String titulos[] = {"Codigo", "Medicinas", "Fecha", "Costo","Dosis", "Importe"};

         t_MedicinaAnimal.setTitulos(titulos);
         t_MedicinaAnimal.cambiarTitulos();
         t_MedicinaAnimal.setFormato(new int[]{4, 0, 3, 4,4,4});
         */

        cargarPuertos();

        stick = new SR232(puertoStick, 1, parent, 3);
        stick.setEID(tf_Eid);   //  tf_Eid::tf_numeroPedido

        stick.start();

        cargarMedicinaAnimal();
        cargarGrupoAnimalUsuario();
        //leerMedicinaAnimal(t_MedicinaAnimal, id_animal);

//        tf_TagID.setText(animal.arete_visual.toString());
        tf_Dosis.textFieldDouble();
//        animalesSeleccionados1.setParent(parent);
        animalesSeleccionados1.reordenar();
        animalesSeleccionados1.setTipo(1);

        this.setTitle(this.getTitle() + " " + rancho.descripcion);

        Image i = null;
        i = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo tru-test.png"));
        setIconImage(i);

        cargarComponentes();
    }

    public void setEid(String recibido) {

        animal.cargarPorEid(recibido);

        animalGrupo = new AnimalGrupo();

        //animalGrupo.id_rancho = rancho.id_rancho;
        animalGrupo.tipo = "medicina";
        animalGrupo.usuario = usuario_activo;

        animalGrupo.grabar(animal);

        cargarGrupoAnimalUsuario();
    }

    private AnimalGrupo animalGrupo;

    public void cargarPuertos() {

        manejadorBD.consulta(
                "SELECT puerto_baston "
                + "FROM configuracion ");

        if (manejadorBD.getRowCount() > 0) {

            puertoStick = manejadorBD.getValorString(0, 0);
        }
    }

    public void cargarGrupoAnimalUsuario() {

        animalGrupo(animalesSeleccionados1.t_animales, usuario_activo, "medicina");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_MedicinaAnimal = new abstractt.Table();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        medicamentoSelector = new abstractt.ComboBox();
        jLabel1 = new javax.swing.JLabel();
        codigoSelector = new abstractt.ComboBox();
        tf_Dosis = new abstractt.TextField();
        selectorFecha = new gui.SelectorFecha();
        jLabel6 = new javax.swing.JLabel();
        tf_costo = new abstractt.TextFieldMoneda();
        tf_Eid = new abstractt.TextField();
        btn_Eliminar = new abstractt.Boton();
        btn_Aplicar = new abstractt.Boton();
        btn_Nuevo = new abstractt.Boton();
        animalesSeleccionados1 = new gui.AnimalesSeleccionados();
        etiqueta1 = new abstractt.Etiqueta();
        plecaSuperior1 = new abstractt.PlecaSuperior();
        fondo1 = new abstractt.fondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplicacion de Medicinas");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 255));
        jSplitPane1.setOpaque(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jSplitPane1, org.jdesktop.beansbinding.ELProperty.create("${resizeWeight}"), jSplitPane1, org.jdesktop.beansbinding.BeanProperty.create("resizeWeight"));
        bindingGroup.addBinding(binding);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_MedicinaAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(t_MedicinaAnimal);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 330, 200));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 500, -1, 100));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dosis:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 60, 20));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Medicamento:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 20));

        medicamentoSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicamentoSelectorActionPerformed(evt);
            }
        });
        jPanel5.add(medicamentoSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Codigo:");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 20));

        codigoSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoSelectorActionPerformed(evt);
            }
        });
        jPanel5.add(codigoSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, -1));

        tf_Dosis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Dosis.setText("0.00");
        jPanel5.add(tf_Dosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1, -1, 100));
        jPanel1.add(selectorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 290, 60));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Costo Total:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 20));

        tf_costo.setFocusable(false);
        jPanel1.add(tf_costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 160, -1));
        jPanel1.add(tf_Eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        btn_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botón eliminar.png"))); // NOI18N
        jPanel1.add(btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));

        btn_Aplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botón gaurdar.png"))); // NOI18N
        jPanel1.add(btn_Aplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        btn_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/botón agregar.png"))); // NOI18N
        jPanel1.add(btn_Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        jPanel6.add(jPanel1);

        jSplitPane1.setLeftComponent(jPanel6);
        jSplitPane1.setRightComponent(animalesSeleccionados1);

        jPanel2.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 120, -1, 525));

        etiqueta1.setForeground(new java.awt.Color(230, 225, 195));
        etiqueta1.setText("Aplicación de medicamento");
        etiqueta1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jPanel2.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        plecaSuperior1.setText("plecaSuperior1");
        jPanel2.add(plecaSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 10, -1, -1));

        fondo1.setText("fondo1");
        jPanel2.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarMedicinaAnimal() {

        System.out.println(animal.id_animal.toString());

      //  if (!animal.id_animal.equals("")) {
        leerMedicinaAnimal(t_MedicinaAnimal, animal);

        manejadorBD.consulta(""
                + "SELECT round(ifnull(sum(round(costo_unitario,2) * dosis),0.00),2) "
                + "FROM  medicina_animal ma, medicina m "
                + "WHERE ma.id_medicina	=	m.id_medicina "
                + "AND   id_rancho	=   '" + rancho.id_rancho + "' "
                + "AND   id_animal	=   '" + animal.id_animal + "'");

        costo = manejadorBD.getValorDouble(0, 0);

        tf_costo.setDouble(costo);
      //  } else {

       //     tf_costo.setDouble(0.0);
        // }
    }

    private void codigoSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoSelectorActionPerformed

        String numero;

        numero = codigoSelector.getSelectedItem().toString();

        if (!numero.equals("")) {

            codigo = Integer.parseInt(numero);

            manejadorBD.consulta(""
                    + "SELECT id_medicina, nombre "
                    + "FROM   medicina "
                    + "WHERE  codigo = " + codigo + " "
                    + "AND    status = 'S'");

            if (manejadorBD.getRowCount() > 0) {

                id_medicina = manejadorBD.getValorString(0, 0);
                medicina = manejadorBD.getValorString(0, 1);
                medicamentoSelector.setSelectedItem(medicina);
            }
        }
    }//GEN-LAST:event_codigoSelectorActionPerformed

    private void medicamentoSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicamentoSelectorActionPerformed

        medicina = this.medicamentoSelector.getSelectedItem().toString();

        manejadorBD.consulta(""
                + "SELECT id_medicina, codigo "
                + "FROM medicina "
                + "WHERE nombre = '" + medicina + "'");

        if (manejadorBD.getRowCount() > 0) {

            id_medicina = manejadorBD.getValorString(0, 0);
            codigo = manejadorBD.getValorInt(0, 1);
            codigoSelector.setSelectedItem(codigo);
        }
    }//GEN-LAST:event_medicamentoSelectorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // this.stick.cerrarPuerto();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.stick.setSeguir(false);
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    public void setAnimal(Animal animal) {
        this.animal = animal;
    }

    private void cargarComponentes() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension pantallaTamano = tk.getScreenSize();
        setSize(pantallaTamano);
        plecaSuperior1.cargar();
        fondo1.cargar(pantallaTamano);
//        jPanel1.setLocation((pantallaTamano.width / 2) - (jPanel1.getWidth() / 2), (pantallaTamano.height / 2) - (jPanel1.getHeight() / 2));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(true);
    }
    Desktop parent;
    private Integer codigo;
    private String id_medicina;
    private String medicina;
    private Double dosis;
    private Date fecha;
    private Double costo;
    private String id_medicina_animal;
    private Animal animal;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.AnimalesSeleccionados animalesSeleccionados1;
    private abstractt.Boton btn_Aplicar;
    private abstractt.Boton btn_Eliminar;
    private abstractt.Boton btn_Nuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private abstractt.ComboBox codigoSelector;
    private abstractt.Etiqueta etiqueta1;
    private abstractt.fondo fondo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private abstractt.ComboBox medicamentoSelector;
    private abstractt.PlecaSuperior plecaSuperior1;
    private gui.SelectorFecha selectorFecha;
    private abstractt.Table t_MedicinaAnimal;
    private abstractt.TextField tf_Dosis;
    private abstractt.TextField tf_Eid;
    private abstractt.TextFieldMoneda tf_costo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * @param animal the animal to set
     */
}
