/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import abstractt.TextField;
import abstractt.fondo;
import java.awt.Frame;
import java.util.Date;

/**
 *
 * @author angelesygil
 */
public class PesoManual extends javax.swing.JFrame {

    /**
     * Creates new form PesoManual
     */
    public PesoManual(EspecificacionesAnimal parent, TextField aEtiqueta) {
        this.parent = parent;
//        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);

        tf_peso.textFieldDouble();

        etiqueta = aEtiqueta;

        fecha_peso = new Date();

        setResizable(false);

        fondo1.cargar(getSize());

    }

    private TextField etiqueta;
    private Date fecha_peso;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tf_peso = new abstractt.TextField();
        selectorFecha1 = new gui.SelectorFecha();
        bnt_Aceptar = new abstractt.Boton();
        etiqueta1 = new abstractt.Etiqueta();
        fondo1 = new abstractt.fondo();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Peso Manual");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_peso.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tf_peso.setText("0.00");
        tf_peso.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jPanel3.add(tf_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 30));
        jPanel3.add(selectorFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, -1));

        bnt_Aceptar.setText("Aceptar");
        bnt_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_AceptarActionPerformed(evt);
            }
        });
        jPanel3.add(bnt_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 80, -1, -1));

        etiqueta1.setBackground(new java.awt.Color(95, 84, 88));
        etiqueta1.setForeground(new java.awt.Color(230, 225, 195));
        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1.setText("Peso Manual");
        etiqueta1.setFont(new java.awt.Font("Trebuchet", 1, 36)); // NOI18N
        etiqueta1.setOpaque(true);
        jPanel1.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 70));

        fondo1.setText("fondo2");
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 215));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnt_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_AceptarActionPerformed
        etiqueta.setDouble(tf_peso.getDouble());
        parent.fecha_peso.setTime(this.selectorFecha1.getFecha());
        this.dispose();
    }//GEN-LAST:event_bnt_AceptarActionPerformed

    EspecificacionesAnimal parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.Boton bnt_Aceptar;
    private javax.swing.ButtonGroup buttonGroup1;
    private abstractt.Etiqueta etiqueta1;
    private abstractt.fondo fondo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private gui.SelectorFecha selectorFecha1;
    private abstractt.TextField tf_peso;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the fecha_peso
     */
    public Date getFecha_peso() {
        return fecha_peso;
    }
}
