/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import abstractt.Table;
import domain.Excel;
import static domain.Movimiento.cargarTraspasos;
import static gui.Desktop.rancho;
import java.util.Date;

/**
 *
 * @author angelesygil
 */
public class RegistroTrasladoGanado extends javax.swing.JFrame {

    /**
     * Creates new form TrasladoGanado
     */
    public RegistroTrasladoGanado(Desktop parent) {
//        super(parent, modal);
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);

        cargarTabla();

        this.buttonGroup1.add(jrb_hoy);
        this.buttonGroup1.add(jrb_todo);
        this.buttonGroup1.add(jrb_otra_fecha);

        this.setTitle(this.getTitle() + " " + rancho.descripcion);
        
        this.setResizable(false);
        
        fondo1.cargar(getSize());

    }

    Table reporte;

    private void cargarTabla() {

        cargarTraspasos(table1, 1, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new abstractt.Table();
        jPanel3 = new javax.swing.JPanel();
        jrb_todo = new javax.swing.JRadioButton();
        jrb_hoy = new javax.swing.JRadioButton();
        jrb_otra_fecha = new javax.swing.JRadioButton();
        btn_reporte = new abstractt.Boton();
        calendar1 = new abstractt.Calendar();
        etiqueta1 = new abstractt.Etiqueta();
        fondo1 = new abstractt.fondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte de Traslados");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setForeground(new java.awt.Color(230, 225, 195));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        table1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(table1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 780, 300));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 5));

        jrb_todo.setBackground(new java.awt.Color(255, 255, 255));
        jrb_todo.setSelected(true);
        jrb_todo.setText("Todo");
        jrb_todo.setOpaque(false);
        jrb_todo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_todoActionPerformed(evt);
            }
        });
        jPanel3.add(jrb_todo);

        jrb_hoy.setBackground(new java.awt.Color(255, 255, 255));
        jrb_hoy.setText("Hoy");
        jrb_hoy.setOpaque(false);
        jrb_hoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_hoyActionPerformed(evt);
            }
        });
        jPanel3.add(jrb_hoy);

        jrb_otra_fecha.setBackground(new java.awt.Color(255, 255, 255));
        jrb_otra_fecha.setText("Otra Fecha");
        jrb_otra_fecha.setOpaque(false);
        jrb_otra_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_otra_fechaActionPerformed(evt);
            }
        });
        jPanel3.add(jrb_otra_fecha);

        btn_reporte.setText("Generar Reportes");
        btn_reporte.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reporteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_reporte);

        calendar1.setEnabled(false);
        calendar1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        calendar1.setMinimumSize(new java.awt.Dimension(100, 30));
        calendar1.setPreferredSize(new java.awt.Dimension(120, 20));
        jPanel3.add(calendar1);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 425, 800, 75));

        etiqueta1.setBackground(new java.awt.Color(95, 84, 88));
        etiqueta1.setForeground(new java.awt.Color(230, 225, 195));
        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1.setText("Registro de Traslado de Ganado");
        etiqueta1.setFont(new java.awt.Font("Trebuchet", 1, 48)); // NOI18N
        etiqueta1.setOpaque(true);
        jPanel1.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 80));

        fondo1.setText("fondo1");
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_todoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_todoActionPerformed

        validarRadioButtons();
    }//GEN-LAST:event_jrb_todoActionPerformed

    private void jrb_hoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_hoyActionPerformed

        validarRadioButtons();
    }//GEN-LAST:event_jrb_hoyActionPerformed

    private void jrb_otra_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_otra_fechaActionPerformed

        validarRadioButtons();
    }//GEN-LAST:event_jrb_otra_fechaActionPerformed

    private void btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reporteActionPerformed

        generarReporte();

    }//GEN-LAST:event_btn_reporteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void generarReporte() {

        Date fecha = new Date();
        Excel excel = new Excel();
        Integer tipo = 0;

        if (jrb_todo.isSelected()) {
            tipo = 1;
            //cargarTraspasos(reporte, 1, null);
        }
        if (jrb_hoy.isSelected()) {
            tipo = 2;
            //cargarTraspasos(reporte, 2, fecha);
        }
        if (jrb_otra_fecha.isSelected()) {
            tipo = 3;
            fecha = this.calendar1.getDate();
            //cargarTraspasos(reporte, 3, fecha);
        }

        reporte = cargarTraspasos(reporte, tipo, fecha);
        excel.reporteTraspasos(reporte, tipo, fecha);

    }

    private void validarRadioButtons() {

        calendar1.setEnabled(false);

        if (jrb_otra_fecha.isSelected()) {
            calendar1.setEnabled(true);
        }
    }
    Desktop parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.Boton btn_reporte;
    private javax.swing.ButtonGroup buttonGroup1;
    private abstractt.Calendar calendar1;
    private abstractt.Etiqueta etiqueta1;
    private abstractt.fondo fondo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jrb_hoy;
    private javax.swing.JRadioButton jrb_otra_fecha;
    private javax.swing.JRadioButton jrb_todo;
    private abstractt.Table table1;
    // End of variables declaration//GEN-END:variables
}
