/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Animal;
import static domain.Animal.cargararete_visuals;
import domain.Corral;
import static domain.Corral.cargarCorrales;
import domain.Excel;
import static domain.Movimiento.cargarMedicinas;
import static domain.Movimiento.cargarPesos;
import static gui.Desktop.rancho;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;

/**
 *
 * @author angelesygil
 */
public class ReporteSesiones extends javax.swing.JFrame {

    /**
     * Creates new form reporteSesiones
     */
    public ReporteSesiones(Desktop parent) {
//        super(parent, modal);
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
        tagIdSelector.addArray(cargararete_visuals());
        this.buttonGroup1.add(jrb_hoy);
        this.buttonGroup1.add(this.jrb_fecha);
        this.buttonGroup1.add(this.jrb_entre_fechas);
        this.buttonGroup1.add(this.jrb_tagId);
        tipo = 1;
        fecha_ini = new Date();
        fecha_fin = new Date();
        animal = new Animal();
        cargarTablas();
        corralSelector1.addArray(cargarCorrales());
        this.setTitle(this.getTitle() + " " + rancho.descripcion);
        
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension pantallaTamano = tk.getScreenSize();
        setResizable(false);
        setSize(pantallaTamano);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        fondo1.cargar(pantallaTamano);
    }

    private void cargarTablas() {
        corral = new Corral();
        corral.cargarPorNombre(corralSelector1.getText(), rancho);
        cargarPesos(t_pesos, tipo, fecha_ini, fecha_fin, animal, corral);
        cargarMedicinas(t_medicinas, tipo, fecha_ini, fecha_fin, animal, corral);
        
        t_pesos.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        t_medicinas.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        
        btn_Reporte.setEnabled(false);

        if (t_pesos.getRowCount() > 0 || t_medicinas.getRowCount() > 0) {

            btn_Reporte.setEnabled(true);
        }

        JTableHeader header = t_pesos.getTableHeader();
        //   header.setBackground(Color.BLUE);
//        header.setForeground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fechas = new javax.swing.JPanel();
        calendar3 = new abstractt.Calendar();
        calendar1 = new abstractt.Calendar();
        calendar2 = new abstractt.Calendar();
        tagIdSelector = new abstractt.ComboBox();
        jrb_tagId = new javax.swing.JRadioButton();
        jrb_entre_fechas = new javax.swing.JRadioButton();
        jrb_fecha = new javax.swing.JRadioButton();
        jrb_hoy = new javax.swing.JRadioButton();
        tablas = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        t_pesos = new abstractt.Table();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_medicinas = new abstractt.Table();
        etiqueta1 = new abstractt.Etiqueta();
        etiqueta2 = new abstractt.Etiqueta();
        botones = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btn_visualiza = new abstractt.Boton();
        btn_Reporte = new abstractt.Boton();
        etiqueta3 = new abstractt.Etiqueta();
        corralSelector1 = new domain.CorralSelector();
        etiqueta4 = new abstractt.Etiqueta();
        fondo1 = new abstractt.fondo();

        setTitle("Reporte de Sesiones");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fechas.setOpaque(false);
        fechas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar3.setEnabled(false);
        fechas.add(calendar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 130, 20));

        calendar1.setEnabled(false);
        fechas.add(calendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 130, 20));

        calendar2.setEnabled(false);
        fechas.add(calendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 130, -1));

        tagIdSelector.setEnabled(false);
        tagIdSelector.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        tagIdSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagIdSelectorActionPerformed(evt);
            }
        });
        fechas.add(tagIdSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, 20));

        jrb_tagId.setBackground(new java.awt.Color(255, 255, 255));
        jrb_tagId.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jrb_tagId.setForeground(new java.awt.Color(95, 84, 88));
        jrb_tagId.setText("Arete Visual");
        jrb_tagId.setOpaque(false);
        jrb_tagId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_tagIdActionPerformed(evt);
            }
        });
        fechas.add(jrb_tagId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 100, 20));

        jrb_entre_fechas.setBackground(new java.awt.Color(255, 255, 255));
        jrb_entre_fechas.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jrb_entre_fechas.setForeground(new java.awt.Color(95, 84, 88));
        jrb_entre_fechas.setText("Entre Fechas");
        jrb_entre_fechas.setOpaque(false);
        jrb_entre_fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_entre_fechasActionPerformed(evt);
            }
        });
        fechas.add(jrb_entre_fechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 100, 20));

        jrb_fecha.setBackground(new java.awt.Color(255, 255, 255));
        jrb_fecha.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jrb_fecha.setForeground(new java.awt.Color(95, 84, 88));
        jrb_fecha.setText("Otra Fecha");
        jrb_fecha.setOpaque(false);
        jrb_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_fechaActionPerformed(evt);
            }
        });
        fechas.add(jrb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 100, 20));

        jrb_hoy.setBackground(new java.awt.Color(255, 255, 255));
        jrb_hoy.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jrb_hoy.setForeground(new java.awt.Color(95, 84, 88));
        jrb_hoy.setSelected(true);
        jrb_hoy.setText("Hoy");
        jrb_hoy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jrb_hoy.setOpaque(false);
        jrb_hoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_hoyActionPerformed(evt);
            }
        });
        fechas.add(jrb_hoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 20));

        jPanel1.add(fechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        tablas.setOpaque(false);
        tablas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSplitPane1.setDividerLocation(600);

        t_pesos.setForeground(new java.awt.Color(230, 225, 195));
        t_pesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane4.setViewportView(t_pesos);

        jSplitPane1.setLeftComponent(jScrollPane4);

        t_medicinas.setForeground(new java.awt.Color(230, 225, 195));
        t_medicinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(t_medicinas);

        jSplitPane1.setRightComponent(jScrollPane1);

        tablas.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 1350, 400));

        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1.setText("Pesos");
        etiqueta1.setFont(new java.awt.Font("Trebuchet", 1, 14)); // NOI18N
        tablas.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta2.setText("Medicinas");
        etiqueta2.setFont(new java.awt.Font("Trebuchet", 1, 14)); // NOI18N
        tablas.add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 750, 30));

        jPanel1.add(tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        botones.setOpaque(false);
        botones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBorder(null);

        jTextPane1.setText("Nota: Primero visualizar la informacion y luego  dar clic en generar el reporte");
        jScrollPane3.setViewportView(jTextPane1);

        botones.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 210, -1));

        btn_visualiza.setText("Visualizar");
        btn_visualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_visualizaActionPerformed(evt);
            }
        });
        botones.add(btn_visualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 30));

        btn_Reporte.setText("Reporte");
        btn_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReporteActionPerformed(evt);
            }
        });
        botones.add(btn_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 30));

        jPanel1.add(botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 100, -1, -1));

        etiqueta3.setBackground(new java.awt.Color(95, 84, 88));
        etiqueta3.setForeground(new java.awt.Color(230, 225, 195));
        etiqueta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta3.setText("Reporte de Sesiones");
        etiqueta3.setFont(new java.awt.Font("Trebuchet", 1, 48)); // NOI18N
        etiqueta3.setOpaque(true);
        jPanel1.add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 80));
        jPanel1.add(corralSelector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, 20));

        etiqueta4.setText("Seleccionar Corral");
        etiqueta4.setFont(new java.awt.Font("Trebuchet", 1, 12)); // NOI18N
        jPanel1.add(etiqueta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        fondo1.setText("fondo1");
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_hoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_hoyActionPerformed
        validarRadioButton();
    }//GEN-LAST:event_jrb_hoyActionPerformed

    private void jrb_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_fechaActionPerformed
        validarRadioButton();
    }//GEN-LAST:event_jrb_fechaActionPerformed

    private void jrb_entre_fechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_entre_fechasActionPerformed
        validarRadioButton();
    }//GEN-LAST:event_jrb_entre_fechasActionPerformed

    private void jrb_tagIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_tagIdActionPerformed
        validarRadioButton();
    }//GEN-LAST:event_jrb_tagIdActionPerformed

    private void tagIdSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagIdSelectorActionPerformed

    }//GEN-LAST:event_tagIdSelectorActionPerformed

    private void visualizarDatos() {

        // Integer tipo = 1;
        tipo = 1;
        fecha_ini = new Date();
        fecha_fin = new Date();
        animal = new Animal();

        if (this.jrb_fecha.isSelected()) {
            tipo = 1;
            fecha_ini = calendar1.getDate();
        }
        if (this.jrb_entre_fechas.isSelected()) {
            tipo = 2;
            fecha_ini = calendar2.getDate();
            fecha_fin = calendar3.getDate();
        }
        if (this.jrb_tagId.isSelected()) {
            tipo = 3;
            animal.cargarPorAreteVisual(this.tagIdSelector.getSelectedItem().toString(), "A");
        }

        cargarTablas();
    }


    private void btn_visualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_visualizaActionPerformed
        visualizarDatos();
    }//GEN-LAST:event_btn_visualizaActionPerformed

    private void btn_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReporteActionPerformed
        generarReporte();
    }//GEN-LAST:event_btn_ReporteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void generarReporte() {

        Excel excel = new Excel();

        excel.reporteSesiones(this.t_pesos, this.t_medicinas, tipo, fecha_ini, fecha_fin, animal);

    }

    private void validarRadioButton() {

        this.calendar1.setEnabled(false);
        this.calendar2.setEnabled(false);
        this.calendar3.setEnabled(false);
        this.tagIdSelector.setEnabled(false);

        if (this.jrb_fecha.isSelected()) {

            this.calendar1.setEnabled(true);
        }
        if (this.jrb_entre_fechas.isSelected()) {
            this.calendar2.setEnabled(true);
            this.calendar3.setEnabled(true);
        }
        if (this.jrb_tagId.isSelected()) {
            this.tagIdSelector.setEnabled(true);
        }

    }
    Desktop parent;
    private Integer tipo;
    private Date fecha_ini;
    private Date fecha_fin;
    private Animal animal;
    private Corral corral;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botones;
    private abstractt.Boton btn_Reporte;
    private abstractt.Boton btn_visualiza;
    private javax.swing.ButtonGroup buttonGroup1;
    private abstractt.Calendar calendar1;
    private abstractt.Calendar calendar2;
    private abstractt.Calendar calendar3;
    private domain.CorralSelector corralSelector1;
    private abstractt.Etiqueta etiqueta1;
    private abstractt.Etiqueta etiqueta2;
    private abstractt.Etiqueta etiqueta3;
    private abstractt.Etiqueta etiqueta4;
    private javax.swing.JPanel fechas;
    private abstractt.fondo fondo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton jrb_entre_fechas;
    private javax.swing.JRadioButton jrb_fecha;
    private javax.swing.JRadioButton jrb_hoy;
    private javax.swing.JRadioButton jrb_tagId;
    private abstractt.Table t_medicinas;
    private abstractt.Table t_pesos;
    private javax.swing.JPanel tablas;
    private abstractt.ComboBox tagIdSelector;
    // End of variables declaration//GEN-END:variables
}
