/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static abstractt.ClaseAbstracta.dialogoConfirmacionSiNo;
import domain.Animal;
import static domain.Animal.animalGrupo;
import static domain.Animal.cargararete_visuals;
import domain.AnimalGrupo;
import static domain.ClaseMovimiento.cargarClaseMovimiento;
import static domain.ClaseMovimiento.idClaseDescripcion;
import static domain.Cliente.cliente;
import static domain.Cliente.idCliente;
import domain.ParametrosSP;
import domain.SR232;
import static gui.Desktop.manejadorBD;
import static gui.Desktop.rancho;
import static gui.Login.gs_mensaje;
import static gui.Login.usuario_activo;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class SalidaGanadoGrupo extends javax.swing.JInternalFrame {

    /**
     * Creates new form SalidaGanadoGrupos
     */
    public SalidaGanadoGrupo(Desktop parent) {
        this.parent = parent;
        initComponents();
        setClosable(true);
        this.pack();
        this.setFrameIcon(new ImageIcon(this.getClass().getResource("/resources/logo tru-test.png")));
        animal = new Animal();
        reporteSalidas = new ReporteSalidas();

        claseMovimientoSelector.addArray(cargarClaseMovimiento());
        clienteSelector1.cargar();

        this.tf_pesoActual.textFieldDouble();

        cargarSalidas();

        cargarPuertos();

        stick = new SR232(puertoStick, 3, parent, 2);
        stick.setEID(tf_Eid);   //  tf_Eid::tf_numeroPedido
        stick.setTf_Peso(tf_pesoActual);
        stick.start();

        cargarGrupoAnimalUsuario();
        animalesSeleccionados1.setParent(parent);
        animalesSeleccionados1.reordenar();
        animalesSeleccionados1.setTipo(2);

        this.setTitle(this.getTitle() + " " + rancho.descripcion);

        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension tamanoPantalla = tk.getScreenSize();
        setResizable(false);
        fondo1.cargar(tamanoPantalla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        etiqueta1 = new abstractt.Etiqueta();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        etiqueta2 = new abstractt.Etiqueta();
        etiqueta3 = new abstractt.Etiqueta();
        etiqueta4 = new abstractt.Etiqueta();
        etiqueta5 = new abstractt.Etiqueta();
        etiqueta6 = new abstractt.Etiqueta();
        calendar1 = new abstractt.Calendar();
        tf_numeroPedido = new abstractt.TextField();
        claseMovimientoSelector = new abstractt.ComboBox();
        tf_pesoActual = new abstractt.TextField();
        btn_salida = new abstractt.Boton();
        btn_Historico = new abstractt.Boton();
        clienteSelector1 = new domain.ClienteSelector();
        jPanel5 = new javax.swing.JPanel();
        animalesSeleccionados1 = new gui.AnimalesSeleccionados();
        tf_Eid = new abstractt.TextField();
        fondo1 = new abstractt.fondo();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Salida de Ganado");
        setPreferredSize(new java.awt.Dimension(1300, 630));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(95, 84, 88));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta1.setForeground(new java.awt.Color(230, 225, 195));
        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1.setText("Información de Salida");
        etiqueta1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jPanel2.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 79));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta2.setText("Fecha de Movimiento: ");
        jPanel4.add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 20));

        etiqueta3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta3.setText("Clase de Movimiento:  ");
        jPanel4.add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 20));

        etiqueta4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta4.setText("Número de pedido:  ");
        jPanel4.add(etiqueta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 150, 20));

        etiqueta5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta5.setText("Cliente: ");
        jPanel4.add(etiqueta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 150, 20));

        etiqueta6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiqueta6.setText("Peso Actual (Kg):  ");
        jPanel4.add(etiqueta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 150, 20));

        calendar1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel4.add(calendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 200, 20));

        tf_numeroPedido.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel4.add(tf_numeroPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, 20));

        claseMovimientoSelector.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel4.add(claseMovimientoSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 200, 20));

        tf_pesoActual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_pesoActual.setText("0.0");
        tf_pesoActual.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel4.add(tf_pesoActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 200, 20));

        btn_salida.setText("Salida de Animales");
        btn_salida.setFont(new java.awt.Font("Trebuchet", 1, 12)); // NOI18N
        btn_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salidaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 150, 30));

        btn_Historico.setText("Historico");
        btn_Historico.setFont(new java.awt.Font("Trebuchet", 1, 12)); // NOI18N
        btn_Historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HistoricoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Historico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 150, 30));
        jPanel4.add(clienteSelector1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 200, 20));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        animalesSeleccionados1.setForeground(new java.awt.Color(230, 225, 195));
        animalesSeleccionados1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel5.add(animalesSeleccionados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));
        jPanel1.add(tf_Eid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fondo1.setText("fondo1");
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarGrupoAnimalUsuario() {

        animalGrupo(animalesSeleccionados1.t_animales, usuario_activo, "salida");
    }

    public void cargarPuertos() {

        manejadorBD.consulta(
                "SELECT puerto_baston, puerto_bascula "
                + "FROM configuracion ");

        if (manejadorBD.getRowCount() > 0) {

            puertoStick = manejadorBD.getValorString(0, 0);
            puertoBascula = manejadorBD.getValorString(0, 1);
        }
    }

    private void agregarSalida() {

        if (animalesSeleccionados1.t_animales.getRowCount() <= 0) {

            JOptionPane.showMessageDialog(this, "No hay animales seleccionados", gs_mensaje, JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        if (dialogoConfirmacionSiNo(this, "¿Esta Seguro que dar salida a los animales?, se dejarán de visualizar en corrales y otras pantallas", gs_mensaje, 1) == 1) {

            return;
        }

        Date fecha;
        SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");

        fecha = this.calendar1.getDate();
        idClaseMovimiento = idClaseDescripcion(this.claseMovimientoSelector.getSelectedItem().toString());
        id_cliente = idCliente(this.clienteSelector1.getSelectedItem().toString());
        numeroPedido = tf_numeroPedido.getText();
        peso_actual = this.tf_pesoActual.getDouble();

        manejadorBD.parametrosSP = new ParametrosSP();

        manejadorBD.parametrosSP.agregarParametro(rancho.id_rancho, "varIdRancho", "STRING", "IN");
        manejadorBD.parametrosSP.agregarParametro(formatoDelTexto.format(fecha), "varFechaSalida", "STRING", "IN");
        manejadorBD.parametrosSP.agregarParametro(idClaseMovimiento.toString(), "varIdClaseMovimiento", "INT", "IN");
        manejadorBD.parametrosSP.agregarParametro(numeroPedido, "varNumeroPedido", "STRING", "IN");
        manejadorBD.parametrosSP.agregarParametro(id_cliente, "varIdCliente", "STRING", "IN");
        manejadorBD.parametrosSP.agregarParametro(peso_actual.toString(), "varPesoActual", "DOUBLE", "IN");
        manejadorBD.parametrosSP.agregarParametro(usuario_activo.id_usuario, "varIdUsuario", "STRING", "IN");

        if (manejadorBD.ejecutarSP("{ call movimientoSalidaGrupo(?,?,?,?,?,?,?) }") == 0) {

            JOptionPane.showMessageDialog(this, "Se Realizo el movimientos de salidas Correctamente", gs_mensaje, JOptionPane.INFORMATION_MESSAGE);
        } else {

            JOptionPane.showMessageDialog(this, "Error al realizar los movimientos de salida\n" + manejadorBD.errorSQL, gs_mensaje, JOptionPane.ERROR_MESSAGE);
        }

        cargarGrupoAnimalUsuario();
        //cargarSalidas();
    }

    private void cargarDatosTag() {

        // arete_electronico = EEid(id_animal);
        tf_Eid.setText(animal.arete_electronico);

        //corral = corralAnimal(id_animal);
        //  tf_corral.setText(animal.corral.nombre);
        //arete_siniiga = areteSiniiga(id_animal);
        // tf_areteSiniiga.setText(animal.arete_siniiga);
    }

    public void cargarSalidas() {

        //   cargarMovimientosSalida(t_movimientoSalida);
    }

    private void btn_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salidaActionPerformed

        agregarSalida();

    }//GEN-LAST:event_btn_salidaActionPerformed

    public void setEid(String eid) {

        //System.out.println("setEid arete_electronico="+arete_electronico);
        animal.cargarPorEid(eid);

        //System.out.println(animal.toString());
        // this.tf_Eid.setText(animal.arete_electronico);
        animalGrupo = new AnimalGrupo();

        //animalGrupo.id_rancho = rancho.id_rancho;
        animalGrupo.tipo = "salida";
        animalGrupo.usuario = usuario_activo;

        animalGrupo.grabar(animal);

        cargarGrupoAnimalUsuario();

        //  tagIdSelector.setSelectedItem(animal.arete_visual);//id_animal.toString());
        //corral = corralAnimal(id_animal);
        //  tf_corral.setText(animal.corral.nombre);//corral);                   
        //arete_siniiga = areteSiniiga(id_animal);
        // tf_areteSiniiga.setText(animal.arete_siniiga);
    }


    private void btn_HistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HistoricoActionPerformed
        if (visualizacionSalidaGanado != null) {

            visualizacionSalidaGanado.dispose();
        }

        visualizacionSalidaGanado = new VisualizacionSalidaGanado(parent);
        visualizacionSalidaGanado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_HistoricoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    public void cargarDatosEid() {

        animal.cargarPorEid(this.tf_Eid.getText());

    }


    String puertoStick, puertoBascula;
    private SR232 stick;
    private Integer idClaseMovimiento;
    private String id_cliente;
    private ReporteSalidas reporteSalidas;
    private VisualizacionSalidaGanado visualizacionSalidaGanado;
    private Integer id_animal;
    private Integer id_corral;
    private String numeroPedido;
    private String corral, eid;
    private String arete_siniiga;
    private Double peso_actual;
    private Animal animal;
    private AnimalGrupo animalGrupo;
    private Desktop parent;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.AnimalesSeleccionados animalesSeleccionados1;
    private abstractt.Boton btn_Historico;
    private abstractt.Boton btn_salida;
    private abstractt.Calendar calendar1;
    private abstractt.ComboBox claseMovimientoSelector;
    private domain.ClienteSelector clienteSelector1;
    private abstractt.Etiqueta etiqueta1;
    private abstractt.Etiqueta etiqueta2;
    private abstractt.Etiqueta etiqueta3;
    private abstractt.Etiqueta etiqueta4;
    private abstractt.Etiqueta etiqueta5;
    private abstractt.Etiqueta etiqueta6;
    private abstractt.fondo fondo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private abstractt.TextField tf_Eid;
    private abstractt.TextField tf_numeroPedido;
    private abstractt.TextField tf_pesoActual;
    // End of variables declaration//GEN-END:variables
}
