/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import static gui.Splash.formatoDate;
import static gui.Splash.formatoDateTime;
import java.util.Date;

/**
 *
 * @author angelesygil
 */
public class SelectorFecha extends javax.swing.JPanel {

    /**
     * Creates new form SelectorFecha
     */
    public SelectorFecha() {
        initComponents();
        this.buttonGroup1.add(jRB_Hoy);
        this.buttonGroup1.add(JRB_OtraFecha);

        fecha_actual = new Date();
        calendar1.setDate(fecha_actual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRB_Hoy = new javax.swing.JRadioButton();
        JRB_OtraFecha = new javax.swing.JRadioButton();
        calendar1 = new abstractt.Calendar();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jRB_Hoy.setBackground(new java.awt.Color(255, 255, 255));
        jRB_Hoy.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRB_Hoy.setForeground(new java.awt.Color(97, 84, 88));
        jRB_Hoy.setSelected(true);
        jRB_Hoy.setText("Hoy");
        jRB_Hoy.setOpaque(false);
        jRB_Hoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_HoyActionPerformed(evt);
            }
        });

        JRB_OtraFecha.setBackground(new java.awt.Color(255, 255, 255));
        JRB_OtraFecha.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        JRB_OtraFecha.setForeground(new java.awt.Color(97, 84, 88));
        JRB_OtraFecha.setText("Otra Fecha");
        JRB_OtraFecha.setOpaque(false);
        JRB_OtraFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB_OtraFechaActionPerformed(evt);
            }
        });

        calendar1.setBackground(new java.awt.Color(255, 255, 255));
        calendar1.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jRB_Hoy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JRB_OtraFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(calendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jRB_Hoy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JRB_OtraFecha)
                    .addComponent(calendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JRB_OtraFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB_OtraFechaActionPerformed

        calendar1.setEnabled(true);

    }//GEN-LAST:event_JRB_OtraFechaActionPerformed

    private void jRB_HoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_HoyActionPerformed

        //if (jRB_Hoy.isSelected()){
        calendar1.setEnabled(false);
        //}

    }//GEN-LAST:event_jRB_HoyActionPerformed

    public Date getFecha() {

        if (jRB_Hoy.isSelected()) {

            System.out.println("Fecha Actual " + fecha_actual);
            return fecha_actual;
        } else {

            System.out.println("Selector Fecha.getFecha " + calendar1.getDate());
            return calendar1.getDate();
        }
    }

    public void setFecha(Date aFecha) {

        calendar1.setDate(aFecha);
        
        String fecha1, fecha2;
        
     //   fecha1 = formatoDate.format(aFecha);

        if (!formatoDate.format(aFecha).equals(formatoDate.format(fecha_actual))) {

            JRB_OtraFecha.setSelected(true);
            calendar1.setEnabled(true);
        } else {
            this.jRB_Hoy.setSelected(true);
            calendar1.setEnabled(false);
        }

    }

    public void setHoy() {

        jRB_Hoy.setSelected(true);
    }

    private Date fecha_actual;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRB_OtraFecha;
    private javax.swing.ButtonGroup buttonGroup1;
    private abstractt.Calendar calendar1;
    private javax.swing.JRadioButton jRB_Hoy;
    // End of variables declaration//GEN-END:variables
}
