package gui;

import domain.Animal;
import static domain.Animal.registrosEmpadre;
import domain.Excel;
import static domain.Medicina.cargarCodigoMedicinas;
import static domain.Medicina.cargarMedicinas;
import static domain.Medicina.leerMedicinaAnimal;
import domain.ParametrosSP;
import domain.TipoParto;
import domain.Tratamiento;
import static gui.Desktop.manejadorBD;
import static gui.Desktop.rancho;
import static gui.Splash.formatoDateTime;
import static gui.Login.gs_mensaje;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Developer GAGS
 */
public class StatusGestacional extends javax.swing.JFrame {

    /**
     * Creates new form MedicinasAnimal
     */
    public StatusGestacional(Animal aAnimal) {
//        super(parent, modal);

        initComponents();
        setLocationRelativeTo(null);
        Image i = null;
        i = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo tru-test.png"));
        setIconImage(i);
        animal = aAnimal;

        //leerMedicinaAnimal(t_MedicinaAnimal, id_animal);
        tf_TagID.setText(animal.arete_visual.toString());

        this.setTitle(this.getTitle() + " " + rancho.descripcion);

        cargarComponentes();

        tipoPartoSelector.cargar();

        System.out.println(animal.id_registro_empadre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_TagID = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel10 = new javax.swing.JLabel();
        tipoPartoSelector = new domain.TipoPartoSelector();
        selectorFecha = new gui.SelectorFecha();
        jRB_Negativo = new javax.swing.JRadioButton();
        jRB_Positivo = new javax.swing.JRadioButton();
        btn_RegistroEmpadre = new abstractt.Boton();
        fondo1 = new abstractt.fondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Status Gestacional");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(97, 84, 88));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(230, 225, 195));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Status Gestacional");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 500, -1, 100));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(64, 37, 4));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Animal (ID Visual)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 150, 20));

        tf_TagID.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        tf_TagID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_TagID.setFocusable(false);
        jPanel1.add(tf_TagID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 160, -1));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 575, 20, 75));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(64, 37, 4));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tipo de Parto:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 140, 20));
        jPanel1.add(tipoPartoSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 160, -1));
        jPanel1.add(selectorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jRB_Negativo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRB_Negativo);
        jRB_Negativo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRB_Negativo.setForeground(new java.awt.Color(64, 37, 4));
        jRB_Negativo.setText("Negativo:                        ");
        jRB_Negativo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRB_Negativo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRB_Negativo.setOpaque(false);
        jRB_Negativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_NegativoActionPerformed(evt);
            }
        });
        jPanel1.add(jRB_Negativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 270, -1));

        jRB_Positivo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jRB_Positivo);
        jRB_Positivo.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jRB_Positivo.setForeground(new java.awt.Color(64, 37, 4));
        jRB_Positivo.setSelected(true);
        jRB_Positivo.setText("Positivo:                        ");
        jRB_Positivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRB_Positivo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jRB_Positivo.setOpaque(false);
        jPanel1.add(jRB_Positivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 300, -1));

        btn_RegistroEmpadre.setText("Guardar");
        btn_RegistroEmpadre.setToolTipText("Estatus de Registro de Empadre Actual");
        btn_RegistroEmpadre.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btn_RegistroEmpadre.setMaximumSize(new java.awt.Dimension(150, 30));
        btn_RegistroEmpadre.setMinimumSize(new java.awt.Dimension(150, 30));
        btn_RegistroEmpadre.setPreferredSize(new java.awt.Dimension(200, 30));
        btn_RegistroEmpadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistroEmpadreActionPerformed(evt);
            }
        });
        jPanel1.add(btn_RegistroEmpadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 190, -1));

        fondo1.setText("fondo1");
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jRB_NegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_NegativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_NegativoActionPerformed

    private void btn_RegistroEmpadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistroEmpadreActionPerformed

        grabar();
    }//GEN-LAST:event_btn_RegistroEmpadreActionPerformed

    private void grabar() {
        
        String status;
        Date fecha;
        TipoParto tipo_parto;

        if (jRB_Positivo.isSelected()) {

            status = "P";
        } else {

            status = "N";
        }

        fecha = selectorFecha.getFecha();
        tipo_parto = this.tipoPartoSelector.getTipoParto();

        if (animal.agregarStatusGestacional(animal.id_registro_empadre, status, fecha, tipo_parto)) {

            JOptionPane.showMessageDialog(this, "Se agrego el status gestacional correctamente", gs_mensaje, JOptionPane.INFORMATION_MESSAGE);
        } else {

            JOptionPane.showMessageDialog(this, "Error al agregar el status gestacional\n" + manejadorBD.errorSQL, gs_mensaje, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cargarComponentes() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension pantallaTamano = tk.getScreenSize();
//        setSize(pantallaTamano);
//        plecaSuperior1.cargar();
        fondo1.cargar(pantallaTamano);
//        jPanel1.setLocation((pantallaTamano.width / 2) - (jPanel1.getWidth() / 2), (pantallaTamano.height / 2) - (jPanel1.getHeight() / 2));
//        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
    }

    private Integer codigo;
    private String id_medicina;
    private String medicina;
    private Double dosis;
    private Date fecha;
    private Double costo;
    private String id_medicina_animal;
    private Animal animal;
    private Tratamiento tratamiento;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.Boton btn_RegistroEmpadre;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.Box.Filler filler1;
    private abstractt.fondo fondo1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRB_Negativo;
    private javax.swing.JRadioButton jRB_Positivo;
    private gui.SelectorFecha selectorFecha;
    private javax.swing.JTextField tf_TagID;
    private domain.TipoPartoSelector tipoPartoSelector;
    // End of variables declaration//GEN-END:variables
}
