/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domain.Animal;
import static domain.Animal.cargarEidsTodos;
import static domain.Animal.cargararete_visuals;
import static domain.Animal.cargararete_visualsMuertos;
import static domain.Animal.cargararete_visualsTodos;
import domain.Excel;
import static domain.Movimiento.cargarMovimientosSalida;
import static domain.Movimiento.cargarMuertes;
import static gui.Desktop.rancho;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author angelesygil
 */
public class VisualizacionSalidaGanado extends javax.swing.JFrame {//JDialog {

    /**
     * Creates new form VisualizacionMuertes
     */
    public VisualizacionSalidaGanado(Desktop parent) {
        //super(parent, modal);
        this.parent = parent;
        initComponents();
        setLocationRelativeTo(null);
        
        tagIdSelector.addArray(Animal.cargArareteVisualStatus("V"));
        this.EIDSelector.addArray(Animal.cargarEidsStatus("V"));
        
        
        
        this.buttonGroup1.add(jrb_hoy);
        this.buttonGroup1.add(this.jrb_fecha);
        this.buttonGroup1.add(this.jrb_entre_fechas);
        this.buttonGroup1.add(this.jrb_tagId);
        this.buttonGroup1.add(this.jrb_EID);

        tipo = 1;
        fecha_ini = new Date();
        fecha_fin = new Date();
        animal = new Animal();
        
        cargarSalidas();

        ListSelectionModel lsm = this.table1.getSelectionModel();

        lsm.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                selectAnimal();
            }
        });
        
        animal_detalles = new Animal();        
        
        this.setTitle(this.getTitle() + " " + rancho.descripcion);
        
        Image i = null;
        i = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/logo tru-test.png"));
        setIconImage(i);
        
        fondo1.cargar(this.getSize());
        setResizable(false);
    }  
    
    private void selectAnimal() {

        Integer fila = table1.getSelectedRow();

        if (fila >= 0) {

            animal_detalles.cargarPorId(table1.getValueAt(fila, 0).toString());
            btn_detalles.setEnabled(true);
        } else {

            btn_detalles.setEnabled(false);
        }
    }

    private void cargarTablaMuertes() {

        cargarMuertes(table1, tipo, fecha_ini, fecha_fin, animal);

        btn_Reporte.setEnabled(false);

        if (table1.getRowCount() > 0) {
            btn_Reporte.setEnabled(true);
        }
    }

    public void cargarSalidas() {

        cargarMovimientosSalida(table1, tipo, fecha_ini, fecha_fin, animal);
        
        btn_Reporte.setEnabled(false);

        if (table1.getRowCount() > 0) {
            btn_Reporte.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        calendar3 = new abstractt.Calendar();
        calendar4 = new abstractt.Calendar();
        EIDSelector = new abstractt.ComboBox();
        tagIdSelector = new abstractt.ComboBox();
        calendar2 = new abstractt.Calendar();
        calendar1 = new abstractt.Calendar();
        jrb_EID = new javax.swing.JRadioButton();
        jrb_tagId = new javax.swing.JRadioButton();
        jrb_entre_fechas = new javax.swing.JRadioButton();
        jrb_fecha = new javax.swing.JRadioButton();
        jrb_hoy = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btn_Reporte = new javax.swing.JButton();
        btn_visualiza = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table1 = new abstractt.Table();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 50), new java.awt.Dimension(0, 50), new java.awt.Dimension(32767, 50));
        btn_detalles = new abstractt.Boton();
        etiqueta1 = new abstractt.Etiqueta();
        fondo1 = new abstractt.fondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Historico de Salidas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        calendar3.setEnabled(false);
        calendar3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel3.add(calendar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 130, 20));

        calendar4.setEnabled(false);
        calendar4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel3.add(calendar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 130, 20));

        EIDSelector.setEnabled(false);
        EIDSelector.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        EIDSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EIDSelectorActionPerformed(evt);
            }
        });
        jPanel3.add(EIDSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, 20));

        tagIdSelector.setEnabled(false);
        tagIdSelector.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        tagIdSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagIdSelectorActionPerformed(evt);
            }
        });
        jPanel3.add(tagIdSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, 20));

        calendar2.setEnabled(false);
        calendar2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel3.add(calendar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 130, -1));

        calendar1.setEnabled(false);
        calendar1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel3.add(calendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, 20));

        jrb_EID.setBackground(new java.awt.Color(255, 255, 255));
        jrb_EID.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jrb_EID.setForeground(new java.awt.Color(95, 84, 88));
        jrb_EID.setText("Arete Electronico");
        jrb_EID.setOpaque(false);
        jrb_EID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_EIDActionPerformed(evt);
            }
        });
        jPanel3.add(jrb_EID, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 130, 20));

        jrb_tagId.setBackground(new java.awt.Color(255, 255, 255));
        jrb_tagId.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jrb_tagId.setForeground(new java.awt.Color(95, 84, 88));
        jrb_tagId.setText("Arete Visual");
        jrb_tagId.setOpaque(false);
        jrb_tagId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_tagIdActionPerformed(evt);
            }
        });
        jPanel3.add(jrb_tagId, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 20));

        jrb_entre_fechas.setBackground(new java.awt.Color(255, 255, 255));
        jrb_entre_fechas.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jrb_entre_fechas.setForeground(new java.awt.Color(95, 84, 88));
        jrb_entre_fechas.setText("Entre Fechas");
        jrb_entre_fechas.setOpaque(false);
        jrb_entre_fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_entre_fechasActionPerformed(evt);
            }
        });
        jPanel3.add(jrb_entre_fechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, 20));

        jrb_fecha.setBackground(new java.awt.Color(255, 255, 255));
        jrb_fecha.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jrb_fecha.setForeground(new java.awt.Color(95, 84, 88));
        jrb_fecha.setText("Otra Fecha");
        jrb_fecha.setOpaque(false);
        jrb_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_fechaActionPerformed(evt);
            }
        });
        jPanel3.add(jrb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 20));

        jrb_hoy.setBackground(new java.awt.Color(255, 255, 255));
        jrb_hoy.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jrb_hoy.setForeground(new java.awt.Color(95, 84, 88));
        jrb_hoy.setSelected(true);
        jrb_hoy.setText("Hoy");
        jrb_hoy.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jrb_hoy.setOpaque(false);
        jrb_hoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_hoyActionPerformed(evt);
            }
        });
        jPanel3.add(jrb_hoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(null);

        jTextPane1.setEditable(false);
        jTextPane1.setBorder(null);
        jTextPane1.setText("Nota: Primero Visualizar la informacion y luego dar click en generar reporte.");
        jScrollPane2.setViewportView(jTextPane1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, -1));

        btn_Reporte.setBackground(new java.awt.Color(64, 37, 4));
        btn_Reporte.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_Reporte.setForeground(new java.awt.Color(230, 225, 195));
        btn_Reporte.setText("Reporte");
        btn_Reporte.setContentAreaFilled(false);
        btn_Reporte.setEnabled(false);
        btn_Reporte.setOpaque(true);
        btn_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReporteActionPerformed(evt);
            }
        });
        jPanel4.add(btn_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, 30));

        btn_visualiza.setBackground(new java.awt.Color(64, 37, 4));
        btn_visualiza.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_visualiza.setForeground(new java.awt.Color(230, 225, 195));
        btn_visualiza.setText("Visualizar      ");
        btn_visualiza.setContentAreaFilled(false);
        btn_visualiza.setOpaque(true);
        btn_visualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_visualizaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_visualiza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, -1, -1));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setForeground(new java.awt.Color(230, 225, 195));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table1);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 300));
        jPanel5.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        btn_detalles.setText("Detalles");
        btn_detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detallesActionPerformed(evt);
            }
        });
        jPanel5.add(btn_detalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 100, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        etiqueta1.setBackground(new java.awt.Color(95, 84, 88));
        etiqueta1.setForeground(new java.awt.Color(230, 225, 195));
        etiqueta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta1.setText("Visualización de Salida de Ganado");
        etiqueta1.setFont(new java.awt.Font("Trebuchet", 1, 48)); // NOI18N
        etiqueta1.setOpaque(true);
        jPanel1.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        fondo1.setText("fondo1");
        jPanel1.add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReporteActionPerformed
        generarReporte();
    }//GEN-LAST:event_btn_ReporteActionPerformed

    private void generarReporte() {

        Excel excel = new Excel();

        excel.reporteSalida(table1);
        
    }

    private void tagIdSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagIdSelectorActionPerformed

    }//GEN-LAST:event_tagIdSelectorActionPerformed

    private void jrb_hoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_hoyActionPerformed
        validarRadioButton();
    }//GEN-LAST:event_jrb_hoyActionPerformed

    private void jrb_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_fechaActionPerformed
        validarRadioButton();
    }//GEN-LAST:event_jrb_fechaActionPerformed

    private void jrb_entre_fechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_entre_fechasActionPerformed
        validarRadioButton();
    }//GEN-LAST:event_jrb_entre_fechasActionPerformed

    private void jrb_tagIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_tagIdActionPerformed
        validarRadioButton();
    }//GEN-LAST:event_jrb_tagIdActionPerformed

    private void btn_visualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_visualizaActionPerformed
        visualizarDatos();
    }//GEN-LAST:event_btn_visualizaActionPerformed

    private void jrb_EIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_EIDActionPerformed
        validarRadioButton();
    }//GEN-LAST:event_jrb_EIDActionPerformed

    private void EIDSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EIDSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EIDSelectorActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btn_detallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detallesActionPerformed

        if (especificacionesAnimal != null) {

            especificacionesAnimal.dispose();
        }

        especificacionesAnimal = new EspecificacionesAnimal(parent);
        especificacionesAnimal.setConsulta(true);

        if (!animal_detalles.id_animal.equals("")) {

            especificacionesAnimal.setId_animal(animal_detalles.id_animal);
        }

        especificacionesAnimal.setVisible(true);
    }//GEN-LAST:event_btn_detallesActionPerformed

    private void visualizarDatos() {

        tipo = 1;
        fecha_ini = new Date();
        fecha_fin = new Date();
        animal = new Animal();

        if (this.jrb_fecha.isSelected()) {

            tipo = 1;
            fecha_ini = calendar1.getDate();
        } else if (this.jrb_entre_fechas.isSelected()) {

            tipo = 2;
            fecha_ini = calendar2.getDate();
            fecha_fin = calendar3.getDate();
        } else if (this.jrb_tagId.isSelected()) {

            tipo = 3;
            animal.cargarPorAreteVisual(this.tagIdSelector.getSelectedItem().toString(),"V");
        } else if (this.jrb_EID.isSelected()) {

            tipo = 4;
            animal.cargarPorAreteElectronicoStatus(this.EIDSelector.getSelectedItem().toString(),"V");
            fecha_ini = calendar4.getDate();
        }

        this.cargarSalidas();
    }

    private void validarRadioButton() {

        this.calendar1.setEnabled(false);
        this.calendar2.setEnabled(false);
        this.calendar3.setEnabled(false);
        this.tagIdSelector.setEnabled(false);
        this.EIDSelector.setEnabled(false);
        this.calendar4.setEnabled(false);

        if (this.jrb_fecha.isSelected()) {

            this.calendar1.setEnabled(true);
        }
        if (this.jrb_entre_fechas.isSelected()) {
            this.calendar2.setEnabled(true);
            this.calendar3.setEnabled(true);
        }
        if (this.jrb_tagId.isSelected()) {
            this.tagIdSelector.setEnabled(true);
        }
        if (this.jrb_EID.isSelected()) {
         
            this.EIDSelector.setEnabled(true);
            this.calendar4.setEnabled(true);
        }
    }
    
    private Animal animal_detalles;
    private Integer tipo;
    private Date fecha_ini;
    private Date fecha_fin;
    private Animal animal;
    EspecificacionesAnimal especificacionesAnimal;
    Desktop parent;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private abstractt.ComboBox EIDSelector;
    private javax.swing.JButton btn_Reporte;
    private abstractt.Boton btn_detalles;
    private javax.swing.JButton btn_visualiza;
    private javax.swing.ButtonGroup buttonGroup1;
    private abstractt.Calendar calendar1;
    private abstractt.Calendar calendar2;
    private abstractt.Calendar calendar3;
    private abstractt.Calendar calendar4;
    private abstractt.Etiqueta etiqueta1;
    private javax.swing.Box.Filler filler1;
    private abstractt.fondo fondo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JRadioButton jrb_EID;
    private javax.swing.JRadioButton jrb_entre_fechas;
    private javax.swing.JRadioButton jrb_fecha;
    private javax.swing.JRadioButton jrb_hoy;
    private javax.swing.JRadioButton jrb_tagId;
    private abstractt.Table table1;
    private abstractt.ComboBox tagIdSelector;
    // End of variables declaration//GEN-END:variables
}
